# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-29 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_type', models.CharField(max_length=45, verbose_name='tipo')),
                ('annotation', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creaci\xf3n')),
            ],
            options={
                'verbose_name': 'anotaci\xf3n',
                'verbose_name_plural': 'anotaciones',
            },
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='nombre')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'anomal\xeda',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'n', 'Normal'), (b'i', 'Integrada'), (b'c', 'Cuadr\xe1tica'), (b'o', 'Original'), (b'd', 'Derivada'), (b'f', 'Filtrada'), (b'r', 'RR')], default=b'n', max_length=2, verbose_name='tipo')),
                ('name', models.CharField(blank=True, default=b'', max_length=50, verbose_name='nombre')),
                ('description', models.TextField(blank=True, default=b'', verbose_name='descripci\xf3n')),
                ('start_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('sampling_rate', models.IntegerField(default=500, verbose_name='Tasa de muestreo')),
            ],
            options={
                'verbose_name': 'canal',
                'verbose_name_plural': 'canales',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(db_index=True)),
                ('y', models.FloatField()),
                ('y_accumulative', models.FloatField(default=0, help_text='La sumatoria de todos los valores                                            "Y" hasta el actual, se calcula con                                            Channel.fill_accumulatives', verbose_name='Y acumulativo')),
                ('wave', models.CharField(blank=True, choices=[(None, b'None'), (b'p', b'p'), (b'q', b'q'), (b'r', b'r'), (b's', b's'), (b'u', b'u')], max_length=1, null=True, verbose_name='onda detectada')),
                ('flagged', models.BooleanField(default=False, verbose_name='marca')),
            ],
            options={
                'verbose_name': 'punto',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creaci\xf3n')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='fecha de modificaci\xf3n')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='patients.Patient', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'registro',
            },
        ),
    ]
