# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-29 20:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='taken_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records_loaded', to=settings.AUTH_USER_MODEL, verbose_name='registrado por'),
        ),
        migrations.AddField(
            model_name='point',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='records.Channel', verbose_name='canal'),
        ),
        migrations.AddField(
            model_name='channel',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='records.Record', verbose_name='registro'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='anomaly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.Anomaly', verbose_name='anomal\xeda'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Point', verbose_name='punto'),
        ),
    ]
