# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-29 20:45
from __future__ import unicode_literals

import apps.patients.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default=b'', verbose_name='descripci\xf3n')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creaci\xf3n')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=apps.patients.models.get_upload_path, verbose_name='Adjunto')),
            ],
            options={
                'verbose_name': 'diagn\xf3stico',
                'verbose_name_plural': 'diagn\xf3sticos',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='nombre')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'nivel educativo',
                'verbose_name_plural': 'niveles educativos',
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='nombre')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'h\xe1bito',
                'verbose_name_plural': 'h\xe1bitos',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('modified_field', models.TextField(default=b'ALL', verbose_name='campo modificado')),
                ('modified_old_value', models.TextField(default=b'', verbose_name='antiguo valor')),
                ('modified_new_value', models.TextField(default=b'', verbose_name='nuevo valor')),
            ],
            options={
                'verbose_name': 'historial de cambios',
                'verbose_name_plural': 'historial de cambios',
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='nombre')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'ocupaci\xf3n',
                'verbose_name_plural': 'ocupaciones',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('chart_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='n\xfamero de historia')),
                ('first_name', models.CharField(max_length=256, verbose_name='nombre')),
                ('last_name', models.CharField(max_length=256, verbose_name='apellido')),
                ('id_card_prefix', models.CharField(choices=[(b'V', b'V'), (b'J', b'J'), (b'G', b'G'), (b'E', b'E')], default=b'V', max_length=1, verbose_name='prefijo de la c\xe9dula')),
                ('id_card_number', models.IntegerField(null=True, verbose_name='c\xe9dula de identidad')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=apps.patients.models.get_upload_path, verbose_name='foto')),
                ('birth_date', models.DateField(verbose_name='fecha de nacimiento')),
                ('birth_place', models.CharField(blank=True, default=b'', max_length=256, verbose_name='lugar de nacimiento')),
                ('gender', models.CharField(choices=[(b'M', 'Masculino'), (b'F', 'Femenino')], max_length=1, verbose_name='sexo')),
                ('dwelling', models.BooleanField(default=True, verbose_name='\xbfPosee vivienda?')),
                ('street', models.TextField(blank=True, default=b'', verbose_name='direcci\xf3n')),
                ('phone_home', models.CharField(blank=True, default=b'', max_length=50, verbose_name='tel\xe9fono casa')),
                ('phone_mobile', models.CharField(blank=True, default=b'', max_length=50, verbose_name='tel\xe9fono m\xf3vil')),
                ('phone_office', models.CharField(blank=True, default=b'', max_length=50, verbose_name='tel\xe9fono oficina')),
                ('marital_status', models.CharField(choices=[(b's', 'Soltero'), (b'm', 'Casado'), (b'w', 'Viudo'), (b'd', 'Divorciado')], default=b's', max_length=1, verbose_name='estado civil')),
                ('personal_record', models.TextField(blank=True, default=b'', verbose_name='antecedentes patol\xf3gicos')),
                ('family_record', models.TextField(blank=True, default=b'', verbose_name='antecedentes familiares')),
                ('physical_exam', models.TextField(blank=True, default=b'', verbose_name='examen f\xedsico')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='patients.Education', verbose_name='educaci\xf3n')),
                ('habits', models.ManyToManyField(blank=True, related_name='patients', to='patients.Habit', verbose_name='h\xe1bitos personales')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='patients.Occupation', verbose_name='ocupaci\xf3n')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='nombre')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'parentesco',
            },
        ),
        migrations.CreateModel(
            name='Ses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='nombre')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'estatus socioecon\xf3mico',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='ses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='patients.Ses', verbose_name='Estatus socioecon\xf3mico'),
        ),
    ]
