# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-29 20:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL, verbose_name='modificado por'),
        ),
        migrations.AddField(
            model_name='history',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='patients.Patient', verbose_name='paciente'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='anomalies',
            field=models.ManyToManyField(to='records.Anomaly', verbose_name='anomal\xedas'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='made_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Hecho por'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='patients.Patient', verbose_name='paciente'),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together=set([('id_card_prefix', 'id_card_number')]),
        ),
    ]
